import type { Metadata } from "next";

import "./globals.css";
import Provider from "@/lib/providers";
import Header from "./components/header";
import { Toaster } from "@/components/ui/sonner";
import { poppinsSans, spaceMono } from "@/app/fonts/fonts";

export const metadata: Metadata = {
  title: "Portfolio Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppinsSans.variable} ${spaceMono.variable} antialiased`}
      >
        <Provider>
          <Header />
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
